name: Release Binaries

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Build for Linux (amd64)
        run: |
          GOOS=linux GOARCH=amd64 go build ./cmd/dockermon -o dockermon-linux-amd64

    #   - name: Build for macOS (amd64)
    #     run: |
    #       GOOS=darwin GOARCH=amd64 go build ./cmd/dockermon -o dockermon-darwin-amd64

    #   - name: Build for macOS (arm64)
    #     run: |
    #       GOOS=darwin GOARCH=arm64 go build ./cmd/dockermon -o dockermon-darwin-arm64

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dockermon-linux-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
